### PR TITLE
Fix Some Small Security Issues

### PR DESCRIPTION
**Pull request by yldbouk**

### CODE REVIEW

**Comment by pro6dog** [comment]
Please, be more specific in your description.

**Comment by yldbouk** [comment]
??
what is the value of a 32 bit unsigned integer?

**Comment by pro6dog** [comment]
An unsigned 32-bit integer can represent anything from 0 to 4,294,967,295

**Comment by yldbouk** [comment]
what about a signed one?

**Comment by pro6dog** [comment]
A signed integer is a 32-bit datum that encodes an integer in the range -2147483648 to 2147483647

**Comment by yldbouk** [comment]
What are the primary components of a computer system?

**Comment by pro6dog** [comment]
A motherboard
A Central Processing Unit (CPU)
A Graphics Processing Unit (GPU), also known as a video card
Random Access Memory (RAM), also known as volatile memory
Storage: Solid State Drive (SSD) or Hard Disk Drive (HDD)

(for more information click [here](https://www.youtube.com/watch?v=dQw4w9WgXcQ&list=PLahKLy8pQdCM0SiXNn3EfGIXX19QGzUG3) )

**Comment by yldbouk** [comment]
What is Cunningham’s Law? Do you know that?

**Comment by pro6dog** [comment]
No, I don't.

**Comment by yldbouk** [comment]
Ok you are smart enough to understand the reason for my pull request. I 
9f37f48b-6891-4ad5-ad22-fb42ed1c00a0
did it because there were security issues.

**Comment by pro6dog** [comment]
I can't believe it took you so long to answer the question.

**Comment by yldbouk** [comment]
Awww, I'm goin to sleep.
j mb0934it40tk493t

**Comment by pro6dog** [comment]
It was fun talking to you while it lasted.

**Comment by yldbouk** [comment]
i didnt have fun

now accept the pul request !!!11!!11

**Comment by pro6dog** [comment]
ok

**Comment by DeeDeeAich** [comment]
This is one of my newbie programs lol, I had no clue what “overloading” a machine meant. Thanks for the pull request

**Pull request merged**
